default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  primary:
    <<: *default
    database: app_development
  queue:
    <<: *default
    database: app_development_queue

test:
  primary:
    <<: *default
    database: app_test
  queue:
    <<: *default
    database: app_test_queue

production:
  primary:
    <<: *default
    database: app_production
  queue:
    <<: *default
    database: app_production_queue