development:
  deadline_check:
    class: DeadlineCheckJob
    schedule: every day at 0:00 Asia/Tokyo

production:
  deadline_check:
    class: DeadlineCheckJob
    schedule: every day at 0:00 Asia/Tokyo
